services:
  - type: web
    name: tds-virtual-ta
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: AIPIPE_TOKEN
        value: <set in dashboard instead of hardcoding>
      - key: PYTHON_VERSION
        value: "3.11"
